version: "3.3"
services:
  ygp-api:
    build:
      context: ./
    environment:
      REDIS_URI: redis://redis:6379
    restart: always
    ports:
    - 8080:8080
    volumes:
    - ./pkg:/app/pkg

  redis:
    image: redis
    ports:
      - "6379:6379"
